<div class="inner-block-newsletter mb-5" style="content-visibility: auto; contain-intrinsic-size: 80px; background-color: #f1e4f2 !important;">
    <form class="form subscribe newsletter-validate-detail" 
          data-mage-init='{"validation":{}}'
          action="<?= $block->getUrl('newsletter/subscriber/new') ?>" 
          method="post">
        <!-- Dynamically generated form key -->
        <?= $block->getBlockHtml('formkey') ?>
        <div class="container-fluid d-flex justify-content-center px-5 py-3">
            
            <h2 class="m-5" style="color: #6f2c91 !important;">Sign Up for Our Newsletter:</h2>
            <div class="align-items-center d-flex w-50">
                <input class="input-text required-entry validate-email p-2 newsletter" 
                    name="email" type="email" placeholder="Email" data-validate="{required:true, 'validate-email':true}" />
                <button class="subs-button" title="Subscribe" type="submit">SUBSCRIBE</button>
            </div>
        </div>
    </form>
</div>
