<?php
/** Get Store URL */
$storeUrl = $block->getUrl(''); 

?>

<html>
<head>
    <title>Vaibhav Jewellers</title>
</head>
<body>
    <div class="top-bar">
        <?php 
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $scopeConfig = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');
            
            $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

            $address = $scopeConfig->getValue('general/store_information/street_line1', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
            
            $phone_number = $scopeConfig->getValue('general/store_information/phone', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

            $gold_18k_price = $scopeConfig->getValue('general/metalprice/gold_18k_price', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
            $gold_22k_price = $scopeConfig->getValue('general/metalprice/gold_22k_price', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
            $gold_24k_price = $scopeConfig->getValue('general/metalprice/gold_24k_price', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

            $silver_price = $scopeConfig->getValue('general/metalprice/silver_price', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
        ?>
        <div class="contact-info">
            <i class="fab fa-whatsapp"></i> +<?php echo $phone_number; ?>
        </div>
        <div class="shipping-info">
            <?php echo $address; ?>
        </div>
    </div>
    <div class="header">
        <div class="left-links">
            <a href="<?php echo $block->getUrl('customer/account/login'); ?>"><i class="fas fa-user-lock"></i> Login</a>
            <a href="<?php echo $block->getUrl('customer/account/create'); ?>"><i class="fas fa-sign-out-alt"></i> Register</a>
            <a href="<?php echo $block->getUrl('wishlist'); ?>"><i class="fas fa-heart"></i> Wishlist</a>
        </div>
        <div class="logo">
            <a class="logo" href="<?= $storeUrl ?>" title="" aria-label="store logo">
                <img src="http://vjapp.com:8080/media/.thumbswysiwyg/logo-converted.jpeg?rand=1738645443" alt="Vaibhav Jewellers Logo" height="50" width="170"/>
            </a>
        </div>
        <div class="right-links">
            <div class="search">
                <!-- <form action="<?php echo $block->getUrl('catalogsearch/result'); ?>" method="get" class="search-form">
                    <input type="text" name="q" placeholder="Search products..." />
                    <button type="submit">Search</button>
                </form> -->
                <a href="#"><i class="fas fa-search"></i></a>
            </div>
            <div class="dropdown">
                <a href="#" class="dropbtns">Metal Rate <i class="fas fa-caret-down"></i></a>
                <div class="dropdown-content">
                    <a href="#" class="m-0">Gold-18k/1g- <?php echo $gold_18k_price; ?></a>
                    <a href="#" class="m-0">Gold-22k/1g- <?php echo $gold_22k_price; ?></a>
                    <a href="#" class="m-0">Gold-24k/1g-  <?php echo $gold_24k_price; ?></a>
                    <a href="#" class="m-0">Silver-1g- <?php echo $silver_price; ?></a>
                </div>
            </div>
            <div class="cart">
                <a href="<?php echo $block->getUrl('checkout/cart'); ?>" class="action showcart"><i class="fas fa-shopping-cart"></i></a>
            </div>
            <div class="currency">
                <a href="#"> <?php echo $storeManager->getStore()->getCurrentCurrencyCode(); ?></a>
            </div>
            
        </div>
    </div>
   
</body>
</html>